//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualStudio.Delphi {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public sealed class Resources {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        private Resources() {
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisualStudio.Delphi.Resources", typeof(Resources).Assembly);
                    _resourceManager = temp;
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Converts CodeGear Delphi projects to Delphi for Visual Studio projects.'.
        /// </summary>
        public static string CONVERT_WizardDescription {
            get {
                return ResourceManager.GetString("CONVERT_WizardDescription", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Convert CodeGear Delphi Projects'.
        /// </summary>
        public static string CONVERT_WizardName {
            get {
                return ResourceManager.GetString("CONVERT_WizardName", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Templates\Imports\Import Existing Delphi Project (dpr).vstemplate'.
        /// </summary>
        public static string ConvertTemplateFile {
            get {
                return ResourceManager.GetString("ConvertTemplateFile", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'DCCCompiler'.
        /// </summary>
        public static string DCCCompiler {
            get {
                return ResourceManager.GetString("DCCCompiler", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Delphi Project (*.dpr)|*.dpr'.
        /// </summary>
        public static string DelphiProjectFilters {
            get {
                return ResourceManager.GetString("DelphiProjectFilters", _resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap DelphiToVS {
            get {
                object obj = ResourceManager.GetObject("DelphiToVS", _resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Dependent File Properties'.
        /// </summary>
        public static string DependentFileNodeProperties {
            get {
                return ResourceManager.GetString("DependentFileNodeProperties", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error'.
        /// </summary>
        public static string ERROR_DialogCaption {
            get {
                return ResourceManager.GetString("ERROR_DialogCaption", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'ImportDelphiProjectFile'.
        /// </summary>
        public static string ImportDelphiPojectFile {
            get {
                return ResourceManager.GetString("ImportDelphiPojectFile", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'ImportDelphiProject'.
        /// </summary>
        public static string ImportDelphiProject {
            get {
                return ResourceManager.GetString("ImportDelphiProject", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Dude you need a CodeGear Delphi project file name that exits.'.
        /// </summary>
        public static string MSG_CodeGearProjectFileNameRequired {
            get {
                return ResourceManager.GetString("MSG_CodeGearProjectFileNameRequired", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Project location path is invalid.'.
        /// </summary>
        public static string MSG_InvalidLocationPath {
            get {
                return ResourceManager.GetString("MSG_InvalidLocationPath", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Invalid solution name.'.
        /// </summary>
        public static string MSG_InvalidSolutionName {
            get {
                return ResourceManager.GetString("MSG_InvalidSolutionName", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Failed to add template file to project.'.
        /// </summary>
        public static string MsgFailedToLoadTemplateFile {
            get {
                return ResourceManager.GetString("MsgFailedToLoadTemplateFile", _resourceCulture);
            }
        }
    }
}
